import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { Instrument_Serif } from 'next/font/google';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const instrumentserif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
});


export { instrumentserif };
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
