// import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { Instrument_Serif } from 'next/font/google';
import "./globals.css";
import ThemeWrapper from './components/ThemeWrapper';

// export const metadata: Metadata = {
//   title: "CalorieSync",
//   description: "Generated by create next app",
// };

const instrumentserif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} antialiased`}>
        <ThemeWrapper>
          {children}
        </ThemeWrapper>
      </body>
    </html>
  );
}

export { instrumentserif };
